### ISSUE TITLE
Make the tests run on Mac

### ISSUE THREAD

**Issue by agouaillard** [webrtcHacks/adapter#259]
**Browsers and versions affected**
For now, chrome and firefox stable.
Testing on macOSX 10.10.5

**Description**
Make the test run on MacOSX.

**Steps to reproduce**
git clone, npm install, BROWSER=chrome BVER=stable npm test

**Expected results**
all good

**Actual results**
Drs-MacBook-Air:adapter agouaillard$ npm install

> webrtc-adapter@1.0.7 prepublish /Users/agouaillard/DEVEL/GITROOT/adapter
> grunt build

Running "browserify:adapterGlobalObject" (browserify) task

> > Bundle ./out/adapter.js created.

Running "browserify:adapterAndNoGlobalObject" (browserify) task

> > Bundle ./out/adapter_no_global.js created.

Running "browserify:adapterNoEdge" (browserify) task

> > Bundle ./out/adapter_no_edge.js created.

Running "browserify:adapterNoEdgeAndNoGlobalObject" (browserify) task

> > Bundle ./out/adapter_no_edge_no_global.js created.

Done, without errors.
npm WARN unmet dependency /Users/agouaillard/DEVEL/GITROOT/adapter/node_modules/testling/node_modules/xhr-write-stream requires concat-stream@'~0.1.0' but will load
npm WARN unmet dependency /Users/agouaillard/DEVEL/GITROOT/adapter/node_modules/testling/node_modules/concat-stream,
npm WARN unmet dependency which is version 1.0.1
npm WARN unmet dependency /Users/agouaillard/DEVEL/GITROOT/adapter/node_modules/testling/node_modules/browserify requires concat-stream@'~1.4.1' but will load
npm WARN unmet dependency /Users/agouaillard/DEVEL/GITROOT/adapter/node_modules/testling/node_modules/concat-stream,
npm WARN unmet dependency which is version 1.0.1
npm WARN unmet dependency /Users/agouaillard/DEVEL/GITROOT/adapter/node_modules/testling/node_modules/browserify requires resolve@'~0.6.1' but will load
npm WARN unmet dependency /Users/agouaillard/DEVEL/GITROOT/adapter/node_modules/testling/node_modules/resolve,
npm WARN unmet dependency which is version 0.4.3
npm WARN unmet dependency /Users/agouaillard/DEVEL/GITROOT/adapter/node_modules/testling/node_modules/browserify requires shell-quote@'~0.0.1' but will load
npm WARN unmet dependency /Users/agouaillard/DEVEL/GITROOT/adapter/node_modules/testling/node_modules/shell-quote,
npm WARN unmet dependency which is version 1.3.3
Drs-MacBook-Air:adapter agouaillard$ vi test/README.md 
Drs-MacBook-Air:adapter agouaillard$ BROWSER=chrome BVER=stable npm test

> webrtc-adapter@1.0.7 test /Users/agouaillard/DEVEL/GITROOT/adapter
> grunt && test/run-tests | faucet

Running "jshint:files" (jshint) task

> > 4 files lint free.

Running "jscs:src" (jscs) task

> > 4 files without code style errors.

Running "browserify:adapterGlobalObject" (browserify) task

> > Bundle ./out/adapter.js created.

Running "browserify:adapterAndNoGlobalObject" (browserify) task

> > Bundle ./out/adapter_no_global.js created.

Running "browserify:adapterNoEdge" (browserify) task

> > Bundle ./out/adapter_no_edge.js created.

Running "browserify:adapterNoEdgeAndNoGlobalObject" (browserify) task

> > Bundle ./out/adapter_no_edge_no_global.js created.

Done, without errors.
- set -e
  ++ dirname ./node_modules/travis-multirunner/setup.sh
- pushd ./node_modules/travis-multirunner
  ++ pwd -P
- SCRIPTPATH=/Users/agouaillard/DEVEL/GITROOT/adapter/node_modules/travis-multirunner
- popd
- case $OSTYPE in
- PLATFORM=mac
  ++ curl -H 'Accept: text/csv' http://browsers.contralis.info/mac/chrome/stable
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  100   121  100   121    0     0     43      0  0:00:02  0:00:02 --:--:--    43
- TARGET_BROWSER=chrome,stable,stable,mac,49.0.2623.110,,https://dl.google.com/chrome/mac/stable/GoogleChrome.dmg,2016-03-30T17:39:02.082Z
  ++ echo chrome,stable,stable,mac,49.0.2623.110,,https://dl.google.com/chrome/mac/stable/GoogleChrome.dmg,2016-03-30T17:39:02.082Z
  ++ cut -d, -f7
- TARGET_URL=https://dl.google.com/chrome/mac/stable/GoogleChrome.dmg
  ++ echo chrome,stable,stable,mac,49.0.2623.110,,https://dl.google.com/chrome/mac/stable/GoogleChrome.dmg,2016-03-30T17:39:02.082Z
  ++ cut -d, -f5
- TARGET_VERSION=49.0.2623.110
- TARGET_PATH=/Users/agouaillard/DEVEL/GITROOT/adapter/node_modules/travis-multirunner/browsers/chrome/49.0.2623.110
- BINPATH=./browsers/bin
- mkdir -p ./browsers/bin
- '[' '!' -d /Users/agouaillard/DEVEL/GITROOT/adapter/node_modules/travis-multirunner/browsers/chrome/49.0.2623.110 ']'
- echo 'getting chrome 49.0.2623.110 from https://dl.google.com/chrome/mac/stable/GoogleChrome.dmg'
- source /Users/agouaillard/DEVEL/GITROOT/adapter/node_modules/travis-multirunner/install-chrome.sh https://dl.google.com/chrome/mac/stable/GoogleChrome.dmg /Users/agouaillard/DEVEL/GITROOT/adapter/node_modules/travis-multirunner/browsers/chrome/49.0.2623.110
  +++ echo https://dl.google.com/chrome/mac/stable/GoogleChrome.dmg
  +++ sed -r 's/^._\/([^\/]_)$/\1/'
  sed: illegal option -- r
  usage: sed script [-Ealn] [-i extension] [file ...]
     sed [-Ealn] [-i extension] [-e script] ... [-f script_file] ... [file ...]
  ++ FNAME=
  ✓ Log suppression
  ✓ Browser version extraction helper
  # Browser identified
  /Users/agouaillard/DEVEL/GITROOT/adapter/node_modules/selenium-webdriver/lib/promise.js:654
  throw error;
  ^

WebDriverError: unknown error: Chrome failed to start: exited abnormally
  (Driver info: chromedriver=2.21.371459 (36d3d07f660ff2bc1bf28a75d1cdabed0983e7c4),platform=Mac OS X 10.10.5 x86_64)
    at WebDriverError (/Users/agouaillard/DEVEL/GITROOT/adapter/node_modules/selenium-webdriver/error.js:27:10)
    at Object.checkLegacyResponse (/Users/agouaillard/DEVEL/GITROOT/adapter/node_modules/selenium-webdriver/error.js:580:13)
    at /Users/agouaillard/DEVEL/GITROOT/adapter/node_modules/selenium-webdriver/lib/webdriver.js:64:13
    at Promise.invokeCallback_ (/Users/agouaillard/DEVEL/GITROOT/adapter/node_modules/selenium-webdriver/lib/promise.js:1329:14)
    at TaskQueue.execute_ (/Users/agouaillard/DEVEL/GITROOT/adapter/node_modules/selenium-webdriver/lib/promise.js:2790:14)
    at TaskQueue.executeNext_ (/Users/agouaillard/DEVEL/GITROOT/adapter/node_modules/selenium-webdriver/lib/promise.js:2773:21)
    at /Users/agouaillard/DEVEL/GITROOT/adapter/node_modules/selenium-webdriver/lib/promise.js:2652:27
    at /Users/agouaillard/DEVEL/GITROOT/adapter/node_modules/selenium-webdriver/lib/promise.js:639:7
    at process._tickCallback (node.js:368:9)
From: Task: WebDriver.createSession()
    at acquireSession (/Users/agouaillard/DEVEL/GITROOT/adapter/node_modules/selenium-webdriver/lib/webdriver.js:62:22)
    at Function.createSession (/Users/agouaillard/DEVEL/GITROOT/adapter/node_modules/selenium-webdriver/lib/webdriver.js:295:12)
    at Driver (/Users/agouaillard/DEVEL/GITROOT/adapter/node_modules/selenium-webdriver/chrome.js:778:38)
    at Builder.build (/Users/agouaillard/DEVEL/GITROOT/adapter/node_modules/selenium-webdriver/builder.js:464:16)
    at Object.buildDriver (/Users/agouaillard/DEVEL/GITROOT/adapter/test/selenium-lib.js:85:8)
    at Test.<anonymous> (/Users/agouaillard/DEVEL/GITROOT/adapter/test/test.js:99:32)
    at Test.bound [as _cb](/Users/agouaillard/DEVEL/GITROOT/adapter/node_modules/tape/lib/test.js:61:32)
    at Test.run (/Users/agouaillard/DEVEL/GITROOT/adapter/node_modules/tape/lib/test.js:77:10)
    at Test.bound [as run](/Users/agouaillard/DEVEL/GITROOT/adapter/node_modules/tape/lib/test.js:61:32)
    at Immediate.next [as _onImmediate](/Users/agouaillard/DEVEL/GITROOT/adapter/node_modules/tape/lib/results.js:70:15)
From: Task: WebDriver.manage().timeouts().setScriptTimeout(5000)
    at Driver.schedule (/Users/agouaillard/DEVEL/GITROOT/adapter/node_modules/selenium-webdriver/lib/webdriver.js:344:17)
    at Timeouts.setScriptTimeout (/Users/agouaillard/DEVEL/GITROOT/adapter/node_modules/selenium-webdriver/lib/webdriver.js:1274:25)
    at Object.buildDriver (/Users/agouaillard/DEVEL/GITROOT/adapter/test/selenium-lib.js:89:36)
    at Test.<anonymous> (/Users/agouaillard/DEVEL/GITROOT/adapter/test/test.js:99:32)
    at Test.bound [as _cb](/Users/agouaillard/DEVEL/GITROOT/adapter/node_modules/tape/lib/test.js:61:32)
    at Test.run (/Users/agouaillard/DEVEL/GITROOT/adapter/node_modules/tape/lib/test.js:77:10)
    at Test.bound [as run](/Users/agouaillard/DEVEL/GITROOT/adapter/node_modules/tape/lib/test.js:61:32)
    at Immediate.next [as _onImmediate](/Users/agouaillard/DEVEL/GITROOT/adapter/node_modules/tape/lib/results.js:70:15)
✓ Browser identifiedate [as _immediateCallback](timers.js:383:17)
not ok 11 no plan found
⨯ fail  1
npm ERR! Test failed.  See above for more details.

**Comment by fippo** [comment]
try my branch from https://github.com/webrtc/adapter/pull/250 -- that skips travis-multirunner on non-linux

**Comment by agouaillard** [comment]
Will do. I'm also looking at the sed -r thingy, which is a GNU sed _only_ feature.

**Comment by agouaillard** [comment]
Works for chrome.

**Comment by agouaillard** [comment]
works for firefox as well. I'm going to close the issue, and we can follow up on PR #250.
