### ISSUE TITLE
1.1.2 UglifyJS Error

### ISSUE THREAD

**Issue by acivan** [webrtcHacks/adapter#308]
ERROR in dep.f7abdebad56e11f5ea0a.js from UglifyJs
Unexpected token: operator (>) [./~/webrtc-adapter/src/js/firefox/getusermedia.js:16,0]

**Comment by KaptenJansson** [comment]
Does this happen in the 1.2.2 adapter release?

**Comment by pdolega** [comment]
Yes I confirm it breaks on latest version - 1.2.2

```
[ Error: student.bundle.js from UglifyJs
  Unexpected token: operator (>) [./~/webrtc-adapter/src/js/firefox/getusermedia.js:16,0]
      at /home/pdolega/projects/mestudent/mestudent/node_modules/webpack/lib/optimize/UglifyJsPlugin.js:128:32
      at Array.forEach (native)
      at Compilation.<anonymous> (/home/pdolega/projects/mestudent/mestudent/node_modules/webpack/lib/optimize/UglifyJsPlugin.js:44:10)
      at Compilation.applyPluginsAsync (/home/pdolega/projects/mestudent/mestudent/node_modules/tapable/lib/Tapable.js:71:13)
      at Compilation.<anonymous> (/home/pdolega/projects/mestudent/mestudent/node_modules/webpack/lib/Compilation.js:567:9)
      at Compilation.next (/home/pdolega/projects/mestudent/mestudent/node_modules/tapable/lib/Tapable.js:67:11)
      at ExtractTextPlugin.<anonymous> (/home/pdolega/projects/mestudent/mestudent/node_modules/extract-text-webpack-plugin/index.js:303:4)
      at Compilation.applyPluginsAsync (/home/pdolega/projects/mestudent/mestudent/node_modules/tapable/lib/Tapable.js:71:13)
      at Compilation.<anonymous> (/home/pdolega/projects/mestudent/mestudent/node_modules/webpack/lib/Compilation.js:563:8)
```

EDIT: Reverting to 1.1.0 seems to work fine.

**Comment by davies147** [comment]
If I am reading the above correctly, then you are including the
'webrtc-adapter' project as a dependency in your own project (fair enough)
but the ''webrtc-adapter' project just became ES6-ified.

I'd guess your build environment cannot handle that.

I am not entirely sure what the solution to that is - Could you 'require' a
pre-compiled ES5 version from the 'gh-pages' branch? Is that even a valid
thing to do?

Just thinking out loud :)
Steve

**Comment by acivan** [comment]
1.2.2

**Comment by KaptenJansson** [comment]
Aha I yes I noticed that we have es6 in one file still. We have added es5 targets, check the out folder.

**Comment by latentflip** [comment]
Just ran into this, but bumping to 1.3.0 seems to have fixed it. +1 on not publishing es6 to npm.

**Comment by KaptenJansson** [comment]
Yeah since lots of build environments are still not using ES6 it caused lots of problems when adapter.js is included as a dependency in other projects, we were naive and thought just creating ES5 build targets would be enough. We will continue to use ES5 onward.
